run-backend-1:
	@echo "Running the the backends 1"
	@go run backend/main.go -p 8080

run-backend-2:
	@echo "Running the the backends 2"
	@go run backend/main.go -p 8081

run-backend-3:
	@echo "Running the the backends 3"
	@go run backend/main.go -p 8082


run:
	@echo "Running the the backends"
	@go run main.go
